### ISSUE TITLE
Output from compare_multi_sorters.get_agreement_sorting doesn't contain "sampling frequency"

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [SpikeInterface/spikecomparison#15]
It would raise exception if **SpikeToolkit.Curation.Threshold_Num_Spikes** is applied to output from **SpikeComparison.Compare_Multi_Sorters.Get_Agreement_Sorting**, as the output wouldn't have attribute 'sampling frequency'. 

Besides, *other output sortings also need to be checked*.

**Comment by samuelgarcia** [comment]
Shoudl be done in #18
