### ISSUE TITLE
Question/Feature Request: just detection 

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikecomparison#37]
Hi, 
Is it possible to get the number of ground truth spikes detected (in any cluster or the unsorted events) by a sorter? And, similarly, the number of spikes that are included in units but doesn't have a corresponding ground truth spike.
It can be useful to analyze the behaviour of the sorters under noise or to test and find parameters to force multiple sorters to find more or less the same spikes.

**Comment by samuelgarcia** [comment]
There is an entire module for that: `spikecomparison` or `spikeinterface.comparison`.

Have a look to this : 
https://spikeinterface.readthedocs.io/en/latest/modules/index.html#comparison-tutorials
https://spikeinterface.readthedocs.io/en/latest/sorters_comparison.html

You can also have a look to theses notebooks that use this module to compare sorters:
https://spikeinterface.github.io/2020/

**Comment by ferchaure** [comment]
Thanks, I didn't see that notebooks.

I know that I could calculate the number of well-detected spikes (that is quite different from well-detected units) for each GT unit if I sum each row of the match_event_count. Then the total amount of FP events are just the number of detected events minus the summary of all the TP. But maybe you already have method for that 

Do you plan to add a column for the unsorted events in the match_event_count matrix?

**Comment by samuelgarcia** [comment]
Internally in spikecomparison you have acces to everything in
```
SpikeComparion.event_counts2
SpikeComparion.event_counts1
SpikeComparion.match_event_count
SpikeComparion.agreement_scores
SpikeComparion.count_score
SpikeComparion.hungarian_match_12
SpikeComparion.best_match_12
SpikeComparion.get_performance()
SpikeComparion.print_performance()
SpikeComparion.print_summary()
```
explore thoses attrs/methods and you will understand how they works.

The GroundTruthComparison is both counting at units level or spike level.

About the unsorted columns it is not plan, feel free to add it.
But it is more easy to retreive spikes from teh methods and then create another spikeextractor based on numpy and run the comparison again.

**Comment by ferchaure** [comment]
> About the unsorted columns it is not plan, feel free to add it.
But it is more easy to retreive spikes from teh methods and then create another spikeextractor based on numpy and run the comparison again.

It makes a lot of sense, and easy to implement thanks! :+1:
