### ISSUE TITLE
Confusion matrix with agreement score.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikecomparison#6]
Now the confusion matrix mainly render TP + one extra line for FN and one extra column for FP.

It could also be usefull and more generix to plot a confusion matrix of the score agreement between all cells. It could help for  SortingComparison (without GT) as well.

If we had this, to avoid problems, we have to be clear on the semantic "confusion_matrix" because they are both "confusion_matrix". One counting TP and the other agreement score.

I propose to add an option in **get_confusion_matrix(..., metric='count_tp' /  'agreement_score')**

What do you think ?

@alejoe91 @magland @mhhennig @magland

**Comment by alejoe91** [comment]
Sounds good! Can you make it?

**Comment by samuelgarcia** [comment]
Yep. This is my favorite module :)
