### ISSUE TITLE
Change agreement score in GroundTruthComparison

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikecomparison#7]
In SpikeComparison, agreement_score is compute as follow:

```score = num_matches / (num1 + num2 - num_matches)```

in short intersect divide by union because we don't have any apriori.

For GroundTruthComparison it should be
```score = num_matches / num_gt```

in short it is more or less the TP that @magland suggest here #5 

In would prefer to keep the TP terminology as before because a spike can be counted only once.
And have another terminology here like "matching_score".

**Comment by samuelgarcia** [comment]
@alejoe91 @magland @colehurwitz @mhhennig 

I finally change my mind on this.

```score = num_matches / (num1 + num2 - num_matches)``` is **OK** even i context of ground truth because it is in fact the "accuracy" (= intersection / union) so both FP and FN count in the match.

With ```score = num_matches / num_gt```, which is the "recall" FP are not taken in account.

Are you OK ?

**Comment by alejoe91** [comment]
Yes. Also because this should be symmetrical for the multisorting comparison, right?

**Comment by colehurwitz** [comment]
It looks good to me, but I don’t really know enough about comparison to have an informed person opinion.

**Comment by samuelgarcia** [comment]
@alejoe91 : I am saying only for GroundTruthCoùparison wich is not used by multisorting. (of course!!)

**Comment by colehurwitz** [comment]
Is multisortingcomparison asymmetric?

**Comment by samuelgarcia** [comment]
No assignement of matching should not be. I think the label only is asymetric and so the counting.
Am I lost also ?

**Comment by mhhennig** [comment]
Sorry, just realised that was nonsense, forget it!
My issue is that very occasionally something like this happens: 
s1_u1 -> s2_u1 -> s3_u1 -> s1_u2
So here we have a result where there are two units from the same sorter are part of a connected group of units. This comes from the agreements.
(let's not discuss this here, it's a different topic)
