### ISSUE TITLE
Use random match probability to compute threshold for each match.

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikecomparison#8]
For each agreement score (#matched_events / #n_gt), we could compute a threshold based on the   probability of having a match given by randomness.

Example:
```
GT: | |   | |     |  | |  |     | | |
T : | | | | | | | | | | | | | | | | | | 
```
In this case T could be matched to GT just because it fires all the time. In case there isn't a better match, this will result in a 100% score, as all Gt spikes are matched. I think we agree this is an uninteded behavior.

So we could try a probabilistic approach: what is the probability of having this score given the statistics of the twp spike trains? Is the agreement score > random agreement score? if so --> accept, else --> discard.

What do you guys think? @magland @samuelgarcia

**Comment by alejoe91** [comment]
here is a simple mathematical framework (basically we want to test if the 'collisions' or 'unitary events' are above random level): https://portal.g-node.org/advanced-course-2017/lib/exe/fetch.php?media=materials:chapter_10.pdf

**Comment by samuelgarcia** [comment]
Yes, I want this. of course :)

As as said the main difficulty here is not to compute the "chance level" given the spike rate and the deta_time but to compute the **distribution of the chance level**.

Because we need something like  score > random agreement score + variability

**Comment by samuelgarcia** [comment]
Finally we stay with a min_acuracy. With min_acuracy=0.1 we should be above chance level.
